"""Image saving with format handling and EXIF watermark."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image

from pixelpoison.image.loader import ImageMeta

EXIF_COMMENT = "Generated by PixelPoison for authorized security testing"


def _tensor_to_pil(tensor: torch.Tensor) -> Image.Image:
    """Convert a (1, 3, H, W) float tensor in [0, 1] to PIL Image."""
    arr = tensor.squeeze(0).clamp(0, 1).permute(1, 2, 0).detach().cpu().numpy()
    arr = (arr * 255).astype(np.uint8)
    return Image.fromarray(arr, mode="RGB")


def save_image(
    adversarial: torch.Tensor,
    clean: torch.Tensor,
    meta: ImageMeta,
    output_path: str,
    output_format: str | None = None,
    jpeg_quality: int = 85,
) -> str:
    """Save an adversarial image to disk.

    If the image was downscaled during loading, maps the perturbation
    back to the original resolution.

    Args:
        adversarial: Adversarial image tensor (1, 3, H, W) in [0, 1].
        clean: Original clean image tensor (1, 3, H, W) in [0, 1].
        meta: Image metadata from loading.
        output_path: Where to save the output.
        output_format: "jpeg", "png", or None (same as input).
        jpeg_quality: JPEG quality level (1-100).

    Returns:
        The resolved output path.
    """
    # Determine output format
    if output_format is None:
        fmt = meta.original_format.lower()
    else:
        fmt = output_format.lower()

    if fmt == "jpg":
        fmt = "jpeg"

    # Compute perturbation
    perturbation = adversarial - clean

    # If image was downscaled for optimization, upsample perturbation to original resolution.
    # The perturbation was optimized at CLIP's native resolution (336px max) for efficiency,
    # then bilinear-upscaled here. This produces a smooth, low-frequency perturbation that
    # is both less perceptible AND more JPEG-robust than high-res optimization.
    if meta.scale_factor < 1.0:
        orig_h, orig_w = meta.original_size
        perturbation = F.interpolate(
            perturbation,
            size=(orig_h, orig_w),
            mode="bilinear",
            align_corners=False,
        )
        # Reload original image at full resolution for applying perturbation
        orig_img = Image.open(meta.original_path).convert("RGB")
        orig_arr = np.array(orig_img, dtype=np.float32) / 255.0
        clean_full = torch.from_numpy(orig_arr).permute(2, 0, 1).unsqueeze(0)
        output_tensor = (clean_full + perturbation).clamp(0, 1)
    else:
        output_tensor = adversarial.clamp(0, 1)

    # Convert to PIL
    pil_img = _tensor_to_pil(output_tensor)

    # Determine final path
    out_path = Path(output_path)
    if not out_path.suffix:
        ext = ".png" if fmt == "png" else ".jpg"
        out_path = out_path.with_suffix(ext)

    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Save with comment metadata (best-effort EXIF watermark)
    pil_img.info["comment"] = EXIF_COMMENT.encode("utf-8")

    if fmt == "jpeg":
        pil_img.save(str(out_path), format="JPEG", quality=jpeg_quality)
    elif fmt == "png":
        pil_img.save(str(out_path), format="PNG")
    elif fmt == "webp":
        pil_img.save(str(out_path), format="WEBP", quality=jpeg_quality)
    else:
        pil_img.save(str(out_path), format="PNG")  # Default to PNG

    return str(out_path.resolve())


def generate_default_output_path(input_path: str, suffix: str = "_adversarial") -> str:
    """Generate an output path by appending a suffix to the input filename."""
    p = Path(input_path)
    return str(p.parent / f"{p.stem}{suffix}{p.suffix}")
